package com.rhpoc.solar_village;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PermitRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("Area (in sq feet)")
	private java.lang.Integer area;

	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String email;

	public PermitRequest() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getArea() {
		return this.area;
	}

	public void setArea(java.lang.Integer area) {
		this.area = area;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public PermitRequest(java.lang.String name, java.lang.String address,
			java.lang.Integer area, java.lang.String email) {
		this.name = name;
		this.address = address;
		this.area = area;
		this.email = email;
	}

}