package com.rhpoc.solar_village;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PermitRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PermitRequest() {
    }




}